spring:
    profiles:
        active: ${activeProfile}
    application:
        name: driverService
    servlet:
        multipart:
            enabled: true
            max-file-size: 20MB
            max-request-size: 20MB
    jpa:
        hibernate:
            ddl-auto: none
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        show-sql: true
        properties:
            hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
            hibernate.id.new_generator_mappings: false
            hibernate:
              jdbc:
                lob:
                  non_contextual_creation: true
    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${masterDbUrl}
        username: ${masterDbUserName}
        password: ${masterDbPassword}
dms:
   baseUrl : http://localhost:8082
   upload : /upload_document
   get : /document


verification:
   callBackUrl : http://localhost:8080/update-verification-status
   baseUrl : http://localhost:8085
   backgroundVerification : /background-check
   mobileVerification :  /mobile-verification
