package com.intuit.driverService.common.enums;

public enum DriverProfileStatus {

    DOCUMENT_UPLOAD_PENDING,
    BACKGROUND_VERIFICATION_PENDING,
    BACKGROUND_VERIFICATION_IN_PROGRESS,
    BACKGROUND_VERIFICATION_SUCCESSFUL,
    BACKGROUND_VERIFICATION_FAILED,
    PROFILE_ACTIVATED,

}
